### ISSUE TITLE
Redo theme

### ISSUE THREAD

**Issue by Lyxnx** [TCDG/scammer-bingo-desktop-java#1]
I'm not great at theming things so if someone whom is better than I did it, it would be appreciated (and don't forget the fact that it would end up looking better)

The file in question is [src/main/resources/theme.css](https://github.com/HexxiumCreations/scammer-bingo-desktop-java/blob/rewrite/src/main/resources/theme.css)

EDIT: anyone is able to do this. It's simple css but with the tags changed.

**Comment by margobra8** [comment]
Hello! I have extended experience with css, however not much with Java! Nevertheless I could help you improve the visual side of your app. Let me know if you want something!

**Comment by Lyxnx** [comment]
If you could help then that would be nice. The css values aren't too different from regular css but only javafx values are accepted (you won't be able to use normal stuff like `border: 1px solid;`

**Comment by JoeTheHuman** [comment]
So, what's with using CSS in Java, if my ask

**Comment by margobra8** [comment]
Yeah its ok I can bare with it

**Comment by Lyxnx** [comment]
I can always give you the equivalent of the javafx tag. @JoeTheHuman css is used in javafx (java 8) for theming applications. It gives you more customisability. If you want I can show you an unthemed version and then you can see how ugly it is,

**Comment by margobra8** [comment]
@Lyxnx one last thing. I cant actually open the .java main file because I don't code in Java and I don't have a Java IDE. I do have Java 1.8 in my PC. How can I open it? Do I need the JDK?

**Comment by Lyxnx** [comment]
The plain java file is like a text file but with a `.java` extension. You could view it in notepad if you wanted (or on here).

**Comment by margobra8** [comment]
@Lyxnx but I want to preview it in some way so I can see if the theming looks ok.

**Comment by margobra8** [comment]
@Lyxnx I did some improvements, can I commit?

**Comment by Lyxnx** [comment]
Make a pr and I'll approve it.

**Comment by margobra8** [comment]
@Lyxnx done

**Comment by floogulinc** [comment]
See #3
